/**
 * Dev Token API Service
 * 
 * Manages development tokens using PocketBase SDK.
 */

import type { DevTokenMetadata } from '../types'
import { getPocketBase } from '../services/pocketbase/client'
import { parsePocketBaseError } from '../utils/error-handler.util'
import { createLogger } from '../utils/logger.util'
import { withResilience } from '../utils/retry.util'

const logger = createLogger('[DevTokenApiService]')

interface DevTokenRecord {
  id: string
  user: string
  name?: string
  token: string
  is_active: boolean
  environment?: 'development' | 'production'
  created: string
  updated: string
}

class DevTokenApiService {
  /**
   * Request a new dev token from the backend
   * SECURITY: Token generation happens on the backend with proper encryption
   */
  async generateDevToken(
    backendUrl: string,
    primaryToken: string,
    tokenName: string,
    userId: string
  ): Promise<DevTokenRecord> {
    return withResilience(
      async () => {
        const pb = getPocketBase(backendUrl)
        
        // Set the auth token to authenticate the request
        pb.authStore.save(primaryToken)
        
        // Request token generation from backend - no client-side generation
        const record = await pb.collection('dev_tokens').create<DevTokenRecord>({
          name: tokenName,
          user: userId,
          is_active: true,
          environment: 'development'
          // Note: 'token' field is generated by backend with proper encryption
        })

        return record
      },
      {
        retry: { maxAttempts: 3, baseDelay: 1000 },
        timeout: 10000
      }
    ).catch(error => {
      logger.error('Failed to generate dev token', error)
      throw parsePocketBaseError(error)
    })
  }

  /**
   * List all dev tokens for the authenticated user (metadata only)
   */
  async listDevTokens(
    backendUrl: string,
    primaryToken: string
  ): Promise<{ tokens: DevTokenMetadata[]; count: number }> {
    try {
      const pb = getPocketBase(backendUrl)
      
      // Set the auth token to authenticate the request
      pb.authStore.save(primaryToken)
      
      // Query dev_tokens collection
      const resultList = await pb.collection('dev_tokens').getList<DevTokenRecord>(1, 50, {
        sort: '-created',
        filter: `is_active = true`
      })

      const tokens: DevTokenMetadata[] = resultList.items.map(item => ({
        id: item.id,
        name: item.name || 'Unnamed Token',
        token: item.token,
        isActive: item.is_active,
        environment: item.environment || undefined,
        createdAt: item.created,
        lastUsed: null
      }))

      return {
        tokens,
        count: resultList.totalItems
      }
    } catch (error) {
      logger.error('Failed to list dev tokens', error)
      throw parsePocketBaseError(error)
    }
  }

  /**
   * Revoke a specific dev token
   */
  async revokeDevToken(
    backendUrl: string,
    primaryToken: string,
    tokenId: string
  ): Promise<void> {
    try {
      const pb = getPocketBase(backendUrl)
      
      // Set the auth token to authenticate the request
      pb.authStore.save(primaryToken)
      
      await pb.collection('dev_tokens').update(tokenId, {
        is_active: false
      })
    } catch (error) {
      logger.error('Failed to revoke dev token', error)
      throw parsePocketBaseError(error)
    }
  }
}

export const devTokenApiService = new DevTokenApiService()

